"""Pydantic schemas package exporting all request and response types."""
from app.schemas.common import ApiResponse, PaginatedResponse, StatusResponse
from app.schemas.auth import (
    Token,
    TokenPayload,
    LoginRequest,
    ApplicantLoginRequest,
    MFASetupResponse,
    MFAVerifyRequest,
    AdminCreate,
    AdminUpdate,
    AdminResponse,
    UserResponse,
)
from app.schemas.recruitment import (
    JobPostingCreate,
    JobPostingUpdate,
    JobPostingResponse,
    ApplicantCreate,
    ApplicantUpdate,
    ApplicantResponse,
    AdvanceStageRequest,
    TestSessionUpdateRequest,
    InterviewScheduleCreate,
    InterviewScheduleResponse,
    KaryawanSementaraResponse,
)
from app.schemas.tests import (
    TestQuestionCreate,
    TestQuestionUpdate,
    TestQuestionResponse,
    TestQuestionCandidateView,
    TestStartRequest,
    TestSubmissionRequest,
    ViolationReportRequest,
    TestSubmissionResponse,
)
from app.schemas.cms import (
    SiteSettingItem,
    SiteSettingsBatch,
    NavMenuItem,
    ContactSubmissionCreate,
    ContactSubmissionResponse,
)

__all__ = [
    "ApiResponse",
    "PaginatedResponse",
    "StatusResponse",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "ApplicantLoginRequest",
    "MFASetupResponse",
    "MFAVerifyRequest",
    "AdminCreate",
    "AdminUpdate",
    "AdminResponse",
    "UserResponse",
    "JobPostingCreate",
    "JobPostingUpdate",
    "JobPostingResponse",
    "ApplicantCreate",
    "ApplicantUpdate",
    "ApplicantResponse",
    "AdvanceStageRequest",
    "TestSessionUpdateRequest",
    "InterviewScheduleCreate",
    "InterviewScheduleResponse",
    "KaryawanSementaraResponse",
    "TestQuestionCreate",
    "TestQuestionUpdate",
    "TestQuestionResponse",
    "TestQuestionCandidateView",
    "TestStartRequest",
    "TestSubmissionRequest",
    "ViolationReportRequest",
    "TestSubmissionResponse",
    "SiteSettingItem",
    "SiteSettingsBatch",
    "NavMenuItem",
    "ContactSubmissionCreate",
    "ContactSubmissionResponse",
]
